title: Anton Yusupov

baseURL: https://antonyusupov.netlify.app/ru
theme: hugo-researcher
disableKinds:
  - taxonomy
  - term
enableEmoji: yes
math: no
googleAnalytics: ''


defaultContentLanguage: en

languages:
  en:
    fontFamily: Tahoma
    fontWeight: Normal
    languageName: English
    title: My Website
    weight: 0
    menu:
      main:
        - name: Main
          url: /
          weight: 1
        - name: About me
          url: /about
          weight: 5
        - name: Resume
          pre: '<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-earmark-person-fill"
            fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd"
            d="M2 2a2 2 0 0 1 2-2h5.293A1 1 0 0 1 10 .293L13.707 4a1 1 0 0 1 .293.707V14a2
            2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm7.5 1.5v-2l3 3h-2a1 1 0 0 1-1-1zM11 8a3 3 0
            1 1-6 0 3 3 0 0 1 6 0zm2 5.755S12 12 8 12s-5 1.755-5 1.755V14a1 1 0 0 0 1
            1h8a1 1 0 0 0 1-1v-.245z"/></svg> '
          url: /resume.pdf
          weight: 0
        - name: Contact
          url: /contact
          weight: 4
        - name: Русский
          url: /ru
          
  ru:
    fontFamily: Tahoma
    fontWeight: Normal
    languageName: Russian
    title: Мой Сайт
    weight: 1
    menu:
      main:
        - name: Главная
          url: /ru
          weight: 1
        - name: Обо мне 
          url: /ru/about
          weight: 4
        - name: Резюме
          pre: '<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-earmark-person-fill"
            fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd"
            d="M2 2a2 2 0 0 1 2-2h5.293A1 1 0 0 1 10 .293L13.707 4a1 1 0 0 1 .293.707V14a2
            2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm7.5 1.5v-2l3 3h-2a1 1 0 0 1-1-1zM11 8a3 3 0
            1 1-6 0 3 3 0 0 1 6 0zm2 5.755S12 12 8 12s-5 1.755-5 1.755V14a1 1 0 0 0 1
            1h8a1 1 0 0 0 1-1v-.245z"/></svg> '
          url: /resume.pdf/
          weight: 4
        - name: Контакты
          url: /ru/contact
          weight: 2
        - name: English
          url: /
          weight: 5
params:

      

logo: ''
style:
  avatarSize: 90px
  colorBlack: '#222222'
  colorRed: '#dc3545'
  pageWidth: 750px
permalinks:
  /: /:filename

markup:
  goldmark:
    renderer:
      unsafe: yes

